"""
Nigerian Pidgin post-processing for speech transcriptions.
Applies corrections and improvements to transcribed text.
"""

import re
import json
from typing import Dict, List
from pathlib import Path


class PidginProcessor:
    """Processes transcribed text to improve Nigerian Pidgin accuracy."""
    
    def __init__(self):
        self.corrections = self._load_corrections()
        self.common_patterns = self._load_patterns()
    
    def _load_corrections(self) -> Dict[str, str]:
        """Load Nigerian Pidgin to English corrections."""
        # Try to load corrections generated by dataset analyzer
        corrections_path = Path(__file__).parent.parent.parent / "data" / "nigerian_corrections.json"
        
        try:
            with open(corrections_path, 'r', encoding='utf-8') as f:
                dataset_corrections = json.load(f)
                print(f"✅ Loaded {len(dataset_corrections)} corrections from dataset analysis")
                
                # Merge with additional hardcoded corrections
                additional_corrections = {
                    'chop': 'eat',
                    'waka': 'walk',
                    'yarn': 'talk',
                    'sabi': 'know',
                    'oya': 'come on',
                    'abeg': 'please',
                    'wahala': 'problem',
                    'palava': 'trouble',
                    'katakata': 'chaos',
                    'gbege': 'problem',
                    'shey': 'right',
                    'abi': 'right',
                    'comot': 'leave',
                    'enter': 'come in',
                    'carry': 'take',
                    'drop': 'put down',
                    'find': 'look for',
                    'hear': 'listen',
                    'see': 'look',
                    'talk': 'speak',
                }
                
                # Combine both dictionaries (dataset takes priority)
                combined_corrections = {**additional_corrections, **dataset_corrections}
                return combined_corrections
                
        except FileNotFoundError:
            print("⚠️ Dataset corrections not found, using fallback corrections")
            # Fallback to basic corrections if file doesn't exist
            return {
                'wetin': 'what',
                'dey': 'are',
                'go': 'will',
                'na': 'is',
                'fit': 'can',
                'chop': 'eat',
                'waka': 'walk',
                'yarn': 'talk',
                'sabi': 'know',
                'abeg': 'please',
            }
    
    def _load_patterns(self) -> List[tuple]:
        """Load common Nigerian Pidgin patterns for replacement."""
        return [
            # (pattern, replacement)
            (r'\bwetin be\b', 'what is'),
            (r'\bwetin dey\b', 'what is'),
            (r'\bhow far\b', 'how are you'),
            (r'\bno wahala\b', 'no problem'),
            (r'\bno problem\b', 'no problem'),
            (r'\bi dey\b', 'I am'),
            (r'\byou dey\b', 'you are'),
            (r'\bwe dey\b', 'we are'),
            (r'\bthey dey\b', 'they are'),
            (r'\bfit do\b', 'can do'),
            (r'\bno fit\b', 'cannot'),
            (r'\bmake i\b', 'let me'),
            (r'\bmake we\b', 'let us'),
        ]
    
    def process_text(self, text: str, apply_corrections: bool = True) -> str:
        """
        Process transcribed text for Nigerian Pidgin improvements.
        
        Args:
            text: Raw transcribed text
            apply_corrections: Whether to apply Pidgin-to-English corrections
            
        Returns:
            Processed text
        """
        if not text:
            return text
        
        # Clean and normalize text
        processed = self._clean_text(text)
        
        # Apply pattern replacements
        processed = self._apply_patterns(processed)
        
        # Apply word-level corrections if requested
        if apply_corrections:
            processed = self._apply_corrections(processed)
        
        # Final cleanup
        processed = self._final_cleanup(processed)
        
        return processed
    
    def _clean_text(self, text: str) -> str:
        """Clean and normalize the text."""
        # Convert to lowercase for processing
        text = text.lower().strip()
        
        # Remove extra whitespace
        text = re.sub(r'\s+', ' ', text)
        
        # Fix common punctuation issues
        text = re.sub(r'\s+([,.!?])', r'\1', text)
        
        return text
    
    def _apply_patterns(self, text: str) -> str:
        """Apply pattern-based replacements."""
        for pattern, replacement in self.common_patterns:
            text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
        
        return text
    
    def _apply_corrections(self, text: str) -> str:
        """Apply word-level corrections."""
        words = text.split()
        corrected_words = []
        
        for word in words:
            # Remove punctuation for lookup, but preserve it
            clean_word = re.sub(r'[^\w]', '', word.lower())
            punctuation = re.sub(r'[\w]', '', word)
            
            # Apply correction if found
            if clean_word in self.corrections:
                corrected_word = self.corrections[clean_word] + punctuation
            else:
                corrected_word = word
            
            corrected_words.append(corrected_word)
        
        return ' '.join(corrected_words)
    
    def _final_cleanup(self, text: str) -> str:
        """Final text cleanup and formatting."""
        # Capitalize first letter
        if text:
            text = text[0].upper() + text[1:] if len(text) > 1 else text.upper()
        
        # Fix spacing around punctuation
        text = re.sub(r'\s+([,.!?])', r'\1', text)
        text = re.sub(r'([,.!?])\s*([a-zA-Z])', r'\1 \2', text)
        
        return text.strip()
    
    def get_pidgin_confidence(self, text: str) -> float:
        """
        Estimate confidence that the text contains Nigerian Pidgin.
        Returns a score between 0 and 1.
        """
        if not text:
            return 0.0
        
        words = text.lower().split()
        pidgin_words = 0
        
        for word in words:
            clean_word = re.sub(r'[^\w]', '', word)
            if clean_word in self.corrections:
                pidgin_words += 1
        
        # Check for common patterns
        pattern_matches = 0
        for pattern, _ in self.common_patterns:
            if re.search(pattern, text, re.IGNORECASE):
                pattern_matches += 1
        
        # Calculate confidence score
        if len(words) == 0:
            return 0.0
        
        word_score = pidgin_words / len(words)
        pattern_score = min(pattern_matches / len(self.common_patterns), 1.0)
        
        # Weighted combination
        confidence = (word_score * 0.7) + (pattern_score * 0.3)
        
        return min(confidence, 1.0)